env:
  TZ: Asia/Hong_Kong
  DEVICE_CODENAME: sky
  BUILD_USER: admin
  BUILD_HOST: XposedHook
  KERNEL_SOURCE: https://github.com/xxirfanx/android_kernel_common_android12-5.10
  KERNEL_BRANCH: mahiru-5-rose_r1
  DEVICE_DEFCONFIG: gki_defconfig
  CIRRUS_CLONE_DEPTH: 1
  CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
  ANYKERNEL: https://github.com/xxirfanx/AnyKernel3
  TG_TOKEN: ENCRYPTED[!9edcd3081be002db985bb813ca9d803aef002564bcca2a513a4b35e96374c1c5dd11ba6fb118abf024f61db4babc334a!]
  TG_CHAT_ID: ENCRYPTED[!693f768ca576838abbb036f8efd169321f2a7f8c2d10a43ecfd74048c66b538a8eda467cf205630b31e60b7023a224bd!]

  # build type kernel Image
  TYPE_IMAGE: Image

  # Build dtbo.img
  BUILD_DTBO: false

  # Toolchain selection: "aosp" or "greenforce",
  USE_CLANG: "greenforce"
  
  # Kernel SU configuration
  KERNELSU: true
  KERNELSU_TYPE: sukisu # Select kernelsu type "rksu" "sukisu" "kernelsunext"
  KERNELSU_BRANCH: susfs-main
  KPM_PATCH: true
  KPM_VERSION: 0.12.0

  # Build optimization
  BUILD_OPTIONS: "-j8"
  CCACHE: true
  CCACHE_DIR: /tmp/ccache

task:
  name: "Kernel Build"
  timeout_in: 3h
  container:
    image: mhmmdfdlyas/dockerfile:k-ubuntu
    cpu: 8
    memory: 32G

  # Cache configuration
  ccache_cache:
    folder: /tmp/ccache
    fingerprint_script: cat .cirrus.yml > /dev/null

  env:
    CCACHE_MAXSIZE: 2G
    CCACHE_COMPRESS: true

  update_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y aria2 gh bc bison flex libssl-dev libelf-dev dwarves cpio xz-utils locales sudo
    - sudo locale-gen en_US.UTF-8
  setup_script:
    - mkdir -p /tmp/ccache
    - ccache -M 2G

  sync_script:
    - ./download.sh

  build_script:
    - ./build.sh

  cleanup_script:
    - ./done.sh
    
