env:
  TZ: Asia/Hong_Kong
  DEVICE_CODENAME: sky
  BUILD_USER: admin
  BUILD_HOST: XposeeHook
  KERNEL_SOURCE: ENCRYPTED[!da82a63b232b5368f478aedb97d7ee9eda7b08275ddc22733f25fb907b8689f2d5cdcc7cfd916a93baa10edda5399a28!]
  KERNEL_BRANCH: mahiru-5-rose_r1
  CIRRUS_CLONE_DEPTH: 1
  CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
  ANYKERNEL: https://github.com/xxirfanx/AnyKernel3
  TG_TOKEN: ENCRYPTED[!9edcd3081be002db985bb813ca9d803aef002564bcca2a513a4b35e96374c1c5dd11ba6fb118abf024f61db4babc334a!]
  TG_CHAT_ID: ENCRYPTED[!693f768ca576838abbb036f8efd169321f2a7f8c2d10a43ecfd74048c66b538a8eda467cf205630b31e60b7023a224bd!]

task:
  name: "Kernel Build.."
  timeout_in: 5h
  stateful: true
  container:
    image: mhmmdfdlyas/dockerfile:k-ubuntu
    cpu: 8
    memory: 32G

  Sync_script:
    - ./download.sh

  Build_kernel_script:
    - ./build.sh
    - ./done.sh

