env:
  TZ: Asia/Hong_Kong
  DEVICE_CODENAME: chime
  BUILD_USER: admin
  BUILD_HOST: xposed
  KERNEL_SOURCE: https://github.com/xxirfanx/android_kernel_common_android12-5.10
  KERNEL_BRANCH: master
  DEVICE_DEFCONFIG: gki_defconfig
  ANYKERNEL: https://github.com/xxirfanx/AnyKernel3
  
  # Telegram Encrypted Secrets (DO NOT CHANGE unless re-encrypting)
  TG_TOKEN: ENCRYPTED[!9edcd3081be002db985bb813ca9d803aef002564bcca2a513a4b35e96374c1c5dd11ba6fb118abf024f61db4babc334a!]
  TG_CHAT_ID: ENCRYPTED[!693f768ca576838abbb036f8efd169321f2a7f8c2d10a43ecfd74048c66b538a8eda467cf205630b31e60b7023a224bd!]

  # Toolchain Configuration
  USE_CLANG: "greenforce" # "aosp" or "greenforce" or "aosp12"
  CLANG_ROOTDIR: /tmp/cirrus-ci-build/clang # Defined here for ccache fingerprint
  AOSP_CLANG_URL: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/603a89415bbb04dff8bc577b95534479ec13fdc5/clang-r574158.tar.gz
  GREENFORCE_CLANG_URL: https://github.com/greenforce-project/greenforce_clang/releases/download/20251012/gf-clang-22.0.0git-20251012.tar.gz
  AOSP12_CLANG_URL: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/42276f8be3ab82a9a71957ca4943872498bdcdee/clang-r416183d.tar.gz

  # Kernel Build Configuration
  TYPE_IMAGE: Image # Build type kernel Image
  BUILD_DTBO: false # Build dtbo.img

  # Kernel SU configuration
  KERNELSU: true
  KERNELSU_TYPE: sukisu # Select kernelsu type "rksu" "sukisu" "kernelsunext"
  KERNELSU_BRANCH: susfs-main
  KPM_PATCH: true
  KPM_VERSION: 0.12.0

  # Build optimization
  BUILD_OPTIONS: "-j16"
  CCACHE: true
  CCACHE_DIR: /tmp/ccache
  CCACHE_MAXSIZE: 2G
  CCACHE_COMPRESS: true

task:
  name: "Kernel Build"
  timeout_in: 3h
  container:
    image: mhmmdfdlyas/dockerfile:k-ubuntu
    cpu: 8
    memory: 32G

  # Cache configuration
  ccache_cache:
    folder: /tmp/ccache
    # Fingerprint includes CLANG_ROOTDIR and its content to ensure cache bust on toolchain change
    fingerprint_script: 
      - cat .cirrus.yml
      - echo "$AOSP_CLANG_URL"
      - echo "$GREENFORCE_CLANG_URL"
      - echo "$AOSP12_CLANG_URL"

  update_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y aria2 ccache libssl-dev ncurses-dev flex bison cpio xz-utils locales sudo
    - sudo locale-gen en_US.UTF-8

  setup_script:
    - mkdir -p /tmp/ccache
    - ccache -M $CCACHE_MAXSIZE
    - ccache -z # Clear statistics for a clean log

  sync_script:
    - ./download.sh

  build_script:
    - ./build.sh

  cleanup_script:
    - ./done.sh
