env:
  TZ: Asia/Hong_Kong
  DEVICE_CODENAME: sky
  BUILD_USER: admin
  BUILD_HOST: XposedHook
  KERNEL_SOURCE: https://github.com/Anything-at-25-00/android_kernel_common_android12-5.10
  KERNEL_BRANCH: mahiru-5-rose_r1
  CIRRUS_CLONE_DEPTH: 1
  CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
  ANYKERNEL: https://github.com/xxirfanx/AnyKernel3
  TG_TOKEN: ENCRYPTED[!9edcd3081be002db985bb813ca9d803aef002564bcca2a513a4b35e96374c1c5dd11ba6fb118abf024f61db4babc334a!]
  TG_CHAT_ID: ENCRYPTED[!693f768ca576838abbb036f8efd169321f2a7f8c2d10a43ecfd74048c66b538a8eda467cf205630b31e60b7023a224bd!]

  # Select toolchain: "aosp" or "greenforce"
  USE_CLANG: "greenforce"

  # Kernel SU
  KERNELSU: true
  # Select kernelsu type "rksu" "sukisu" "kernelsunext"
  KERNELSU_TYPE: sukisu
  KERNELSU_BRANCH: susfs-main

task:
  name: "Kernel Build.."
  timeout_in: 3h
  container:
    image: mhmmdfdlyas/dockerfile:k-ubuntu
    cpu: 8
    memory: 32G

  update_script:
    - apt-get update
    - apt-get install aria2 -y

  sync_script:
    - ./download.sh

  buildl_script:
    - ./build.sh
    - ./done.sh
